### ISSUE TITLE
piece down only by 1

### ISSUE THREAD

**Issue by ResetXD** [dzshn/python-tetris#22]
is there a way to only move the tetris piece by 1 per every tick() method call?

**Comment by g3ner1c** [comment]
`tick()` is meant to be used in a loop to update the the game continously
Calling `tick()` essentially just updates `BaseGame` using its `gravity` object
So if you waited longer than how long `gravity` takes to move a piece by 2 rows before calling `tick()`, it will look like the piece suddenly jumped rows

Here's an example from [`examples/cli.py`](https://github.com/dzshn/python-tetris/blob/ba224981d304d10822a3eb31e4fbfbff4a37376c/examples/cli.py#L145):
```py
    while True:
        render()
        game.tick()
        ...
        ...

        time.sleep(1 / 120)
```

**Comment by ResetXD** [comment]
So is there a way to have manual update where unless called it wont update? Gravity doesnt seem to be helpful to me though
