### ISSUE TITLE
PyPi package problem

### ISSUE THREAD

**Issue by BilakshanP** [dzshn/python-tetris#8]
ERROR: Could not find a version that satisfies the requirement tetris (from versions: none)
ERROR: No matching distribution found for tetris

**Comment by dzshn** [comment]
A lot of things could cause this, is your pip up-to-date? are there any other logs?

**Comment by dzshn** [comment]
It's been quite a while, I'll close the issue as stale. I think it's most likely this is caused due to having an incompatible python version, if not, please let me know.
